/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSettings: typeof import('./src/components/AiSettings.vue')['default']
    Analytics: typeof import('./src/components/Analytics.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BotCommands: typeof import('./src/components/BotCommands.vue')['default']
    ChatModeration: typeof import('./src/components/ChatModeration.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    StreamTools: typeof import('./src/components/StreamTools.vue')['default']
  }
}
